import "@/app/globals.css";
import type { Metadata } from "next";
import Head from "next/head";
import { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Toaster />
      <head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="description" content="Nhom 6" />
        <title>Mimo clone</title>
      </head>
      <body className="bg-background min-h-screen">{children}</body>
    </html>
  );
}
